### ISSUE TITLE
CoursesManager: №3 Ошибка при десериализации файлов загрузки

### ISSUE THREAD

**Issue by FoxHanter** [romarioGI/CoursesManager#29]
1) создаем пустой .txt файл
2) меняем расширение на .bin
3) нажимаем на кнопку Load и пытаемся выбрать наш файл
4) программа выдает ошибку при работе в режиме Debug
![default](https://user-images.githubusercontent.com/40995369/50297016-d2cb9280-048c-11e9-8d0b-e36848e82522.png)
либо вылетит, если мы запускали .exe файл программы
![default](https://user-images.githubusercontent.com/40995369/50297343-a95f3680-048d-11e9-9ea7-d7ea1546a6bc.png)
5)проделываем такие же действия как в пунктах 1-3 но в файл пишем любой текст, например
![default](https://user-images.githubusercontent.com/40995369/50297134-1920f180-048d-11e9-801f-7827179f9be7.png)
6) программа выдает ошибку
![default](https://user-images.githubusercontent.com/40995369/50297176-30f87580-048d-11e9-9a0d-17e662a22165.png)
либо вылетит, если мы запускали .exe файл программы
![default](https://user-images.githubusercontent.com/40995369/50297343-a95f3680-048d-11e9-9ea7-d7ea1546a6bc.png)

**Comment by romarioGI** [comment]
Добавлена проверка. Если файл не удалось десериализовать, то выводится сообщение о неудачной загрузке.
